# .github/workflows/deploy-api-gateway.yml
name: Deploy API Gateway Service

on:
  workflow_call: # Cho phép được gọi từ workflow khác
  push:
    branches:
      - master
    paths:
      - 'api-gateway/**'
      - '.github/workflows/deploy-api-gateway.yml'
  workflow_dispatch:

jobs:
  build-and-deploy-api-gateway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Maven Clean and Package API Gateway
        run: mvn clean package -DskipTests
        working-directory: ./api-gateway

      # ==========================================================
      # TẠO docker-compose.yml CHỈ CHO API GATEWAY TRÊN RUNNER
      # ==========================================================
      - name: Create docker-compose.yml on runner
        run: |
          cat <<EOF > docker-compose.yml
          version: '3.8'
          name: planbook-api-gateway-stack # Tên stack duy nhất cho API Gateway

          services:
            api-gateway:
              build:
                context: ./api-gateway # Build context là thư mục api-gateway
                dockerfile: Dockerfile # Dockerfile nằm trong thư mục api-gateway
              image: planbook-api-gateway:latest # Tên image
              container_name: planbook-api-gateway
              restart: always
              ports:
                - "8080:8080" # API Gateway lắng nghe trên cổng 8080 của VPS
              environment:
                # Các biến môi trường cần thiết cho API Gateway
                SPRING_PROFILES_ACTIVE: "prod"
                SERVER_PORT: 8080 # Cổng nội bộ của API Gateway
                SPRING_APPLICATION_NAME: "api-gateway"
                # Backend service URL - trỏ đến backend đang chạy trên port 8081
                BACKEND_SERVICE_URL: "http://${{ secrets.VPS_HOST }}:8081"
                # Auth service URL - sẽ được cập nhật khi auth service được deploy
                AUTH_SERVICE_URL: "http://${{ secrets.VPS_HOST }}:8082"
                # Kafka configuration
                SPRING_KAFKA_BOOTSTRAP_SERVERS: "${{ secrets.VPS_HOST }}:9092"
                # Redis configuration cho session management
                SPRING_DATA_REDIS_HOST: "${{ secrets.VPS_HOST }}"
                SPRING_DATA_REDIS_PORT: "6379"
                # Logging
                LOGGING_LEVEL_ROOT: "INFO"
                LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY: "DEBUG"
              networks:
                - planbook-gateway-network
              healthcheck:
                test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
                interval: 30s
                timeout: 10s
                retries: 3

          networks:
            planbook-gateway-network:
              driver: bridge
          EOF
        shell: bash

      - name: Copy API Gateway Files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "api-gateway/, docker-compose.yml"
          target: /var/www/api-gateway/

      - name: Stop and Remove Old API Gateway Container on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Đảm bảo thư mục đích tồn tại trên VPS trước khi cd vào
            sudo mkdir -p /var/www/api-gateway
            sudo chown -R ${{ secrets.VPS_USER }}:${{ secrets.VPS_USER }} /var/www/api-gateway

            cd /var/www/api-gateway || { echo "Error: /var/www/api-gateway directory not found on VPS."; exit 1; }
            
            echo "Checking and freeing up port 8080..." # Cổng mà API Gateway sẽ chiếm
            PORT_TO_FREE=8080
            PID_ON_PORT=$(sudo lsof -t -i :$PORT_TO_FREE 2>/dev/null || true)
            if [ -n "$PID_ON_PORT" ]; then
              echo "Found process on port $PORT_TO_FREE with PID: $PID_ON_PORT. Attempting to kill it..."
              sudo kill -9 $PID_ON_PORT 2>/dev/null || true
              sleep 1
              if sudo lsof -i :$PORT_TO_FREE > /dev/null 2>&1; then
                echo "Warning: Port $PORT_TO_FREE is still in use after killing process. Manual intervention may be needed."
              else
                echo "Port $PORT_TO_FREE is now free."
              fi
            else
              echo "Port $PORT_TO_FREE is already free."
            fi

            echo "Stopping and removing old API Gateway Docker Compose stack if it exists..."
            # Sử dụng --project-name để chỉ dừng stack của API Gateway
            docker compose -f docker-compose.yml --project-name planbook-api-gateway-stack down --remove-orphans 2>/dev/null || true

            echo "Cleaning up old API Gateway image if it exists..."
            docker rmi planbook-api-gateway:latest 2>/dev/null || true

            echo "Old API Gateway container and image cleaned up."

      - name: Start API Gateway with Docker Compose on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/api-gateway || { echo "Error: /var/www/api-gateway directory not found on VPS."; exit 1; }
            echo "Building and starting API Gateway Docker Compose services..."
            # Sử dụng --project-name để chỉ khởi động stack của API Gateway
            docker compose -f docker-compose.yml --project-name planbook-api-gateway-stack up --build -d --remove-orphans
            
            echo "Waiting for API Gateway to be ready..."
            sleep 20
            
            echo "Checking API Gateway health..."
            docker compose -f docker-compose.yml --project-name planbook-api-gateway-stack ps
            
            echo "API Gateway started successfully!"
            echo "API Gateway: http://${{ secrets.VPS_HOST }}:8080"
            echo ""
            echo "Use 'docker compose -f docker-compose.yml --project-name planbook-api-gateway-stack logs -f planbook-api-gateway' to monitor logs."