# File: .github/workflows/deploy-all-service.yml
# PHIÊN BẢN CUỐI CÙNG ĐÃ SỬA LỖI

name: Orchestrate All Services Deployment

on:
  push:
    branches:
      - master
    paths:
      - 'api-gateway/**'
      - 'auth-service/**'
  workflow_dispatch:

jobs:
  deploy_auth_service:
    # SỬA LỖI: Đã xóa "@master" ở cuối dòng này.
    uses: ./.github/workflows/reusable/deploy-auth-service.yml
    with:
      service_path: auth-service
      vps_target_path: /var/www/auth-service/
    secrets:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      PRIVATE_KEY_PEM: ${{ secrets.PRIVATE_KEY_PEM }}
      PUBLIC_KEY_PEM: ${{ secrets.PUBLIC_KEY_PEM }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      SUPABASE_JWT_SECRET_KEY: ${{ secrets.SUPABASE_JWT_SECRET_KEY }}
      SPRING_APP_SECRET_KEY: ${{ secrets.SPRING_APP_SECRET_KEY }}
      KAFKA_TOPIC: ${{ secrets.KAFKA_TOPIC }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      APP_DURATION: ${{ secrets.APP_DURATION }}

  deploy_api_gateway:
    needs: [deploy_auth_service]
    # SỬA LỖI: Đã xóa "@master" ở cuối dòng này.
    uses: ./.github/workflows/reusable/deploy-api-gateway.yml
    with:
      service_path: api-gateway
      vps_target_path: /var/www/api-gateway/
    secrets:
      VPS_HOST: ${{ secrets.VPS_HOST }}
      VPS_USER: ${{ secrets.VPS_USER }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}