name: Deploy Spring Boot Backend with Docker Swarm (CI/CD)

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Bước này cần thiết để tạo ra file JAR
      - name: Maven Clean and Package
        run: mvn clean package -DskipTests

      # Bước này tạo file docker-compose.yml động trên runner
      # Sẽ loại bỏ 'build' và chỉ định image cục bộ
      - name: Create docker-compose.yml on runner
        run: |
          cat <<EOF > docker-compose.yml
          version: '3.8'

          services:
            zookeeper:
              image: zookeeper:latest
              container_name: zookeeper
              restart: always
              ports:
                - "2181:2181"
              environment:
                ZOO_CLIENT_PORT: 2181 

            kafka:
              image: confluentinc/cp-kafka:7.5.0
              container_name: kafka
              restart: always
              ports:
                - "9092:9092"
              environment:
                KAFKA_BROKER_ID: 1
                KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
                KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
                KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
                KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
                KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
              depends_on:
                - zookeeper

            kafdrop:
              image: obsidiandynamics/kafdrop:latest
              container_name: kafdrop
              restart: always
              ports:
                - "9000:9000"
              environment:
                KAFKA_BROKERCONNECT: kafka:29092
                JVM_OPTS: "-Xms16M -Xmx48M"
              depends_on:
                - kafka

            redis:
              image: redis:latest
              container_name: redis
              restart: always
              ports:
                - "6379:6379"

            backend:
              # KHÔNG CÓ KHỐI 'build' ở đây
              image: planbook-be:latest # <-- Giữ nguyên tên image cục bộ
              restart: always
              ports:
                - "8080:8080"
              depends_on:
                - zookeeper
                - kafka
                - redis
              healthcheck:
                test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
                interval: 30s
                timeout: 10s
                retries: 3
                start_period: 60s
              deploy:
                replicas: 1
                update_config:
                  parallelism: 1
                  delay: 10s
                  order: start-first
                rollback_config:
                  parallelism: 1
                  delay: 10s
                  order: stop-first
                restart_policy:
                  condition: on-failure
          EOF
        shell: bash

      # Bước này copy tất cả file cần thiết lên VPS
      - name: Copy Project Files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: /var/www/be/

      # BƯỚC TRIỂN KHAI THỰC TẾ VỚI DOCKER STACK (Swarm Mode)
      - name: Deploy Application with Docker Stack on VPS (Swarm Mode)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e # Exit immediately if a command exits with a non-zero status.

            cd /var/www/be || { echo "Error: /var/www/be directory not found on VPS."; exit 1; }
            echo "Deploying application using Docker Stack (Swarm Mode)..."

            # 1. Dọn dẹp ban đầu các container Docker Compose cũ (không phải Swarm-managed)
            echo "Attempting to clean up old standalone Docker Compose containers (if any)..."
            docker compose -f docker-compose.yml down -v --remove-orphans --timeout 0 2>/dev/null || true
            docker stop planbook-be zookeeper kafka kafdrop redis 2>/dev/null || true
            docker rm -f planbook-be zookeeper kafka kafdrop redis 2>/dev/null || true
            # KHÔNG XÓA IMAGE CŨ Ở ĐÂY NỮA, VÌ CHÚNG TA SẼ BUILD LẠI NÓ.
            # docker rmi planbook-be:latest 2>/dev/null || true 
            echo "Old containers cleaned up (if any)."

            # THÊM BƯỚC BUILD IMAGE TRỰC TIẾP TRÊN VPS TẠI ĐÂY
            echo "Building Docker image 'planbook-be:latest' directly on VPS..."
            docker build -t planbook-be:latest . || { echo "Error: Docker image build failed on VPS."; exit 1; }
            echo "Docker image built successfully on VPS."

            # 2. Export environment variables cho docker stack deploy
            export SPRING_DATASOURCE_URL="${{ secrets.DB_URL }}"
            export SPRING_DATASOURCE_USERNAME="${{ secrets.DB_USERNAME }}"
            export SPRING_DATASOURCE_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export SUPABASE_JWT_SECRET="${{ secrets.SUPABASE_JWT_SECRET_KEY }}"
            export SPRING_SECRETKEY="${{ secrets.SPRING_APP_SECRET_KEY }}"
            export KAFKA_TOPIC_NAME="${{ secrets.KAFKA_TOPIC }}"
            export SPRING_MAIL_HOST="${{ secrets.MAIL_HOST }}"
            export SPRING_MAIL_PORT="${{ secrets.MAIL_PORT }}"
            export SPRING_MAIL_USERNAME="${{ secrets.MAIL_USERNAME }}"
            export SPRING_MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}"
            export SPRING_DATA_REDIS_HOST="redis"
            export SPRING_DATA_REDIS_PORT="6379"
            export SPRING_CACHE_TYPE="redis"
            export SPRING_DURATION="${{ secrets.APP_DURATION }}"
            export SPRING_PROFILES_ACTIVE="prod"

            # 3. Triển khai hoặc cập nhật stack
            echo "Running docker stack deploy..."
            docker stack deploy -c docker-compose.yml planbook-stack 

            echo "Deployment initiated. Check service status with 'docker service ls' and logs with 'docker service logs planbook-stack_backend'"
            echo "Waiting for 'planbook-stack_backend' service to be stable..."

            # 4. Kiểm tra trạng thái của dịch vụ sau khi deploy
            ATTEMPTS=0
            MAX_ATTEMPTS=60
            SERVICE_NAME="planbook-stack_backend"

            while [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
              SERVICE_EXISTS=$(docker service ls --filter name="$SERVICE_NAME" --format "{{.Name}}" | wc -l)
              if [ "$SERVICE_EXISTS" -eq 0 ]; then
                echo "  Attempt $((ATTEMPTS+1))/$MAX_ATTEMPTS: Service '$SERVICE_NAME' does not exist yet. Waiting..."
                sleep 5
                ATTEMPTS=$((ATTEMPTS+1))
                continue
              fi

              REPLICAS_EXPECTED=$(docker service inspect "$SERVICE_NAME" --format '{{.Spec.Mode.Replicated.Replicas}}' 2>/dev/null || echo 0)
              if [ "$REPLICAS_EXPECTED" -eq 0 ]; then
                REPLICAS_EXPECTED=1
              fi

              RUNNING_REPLICAS=$(docker service ps "$SERVICE_NAME" --filter "desired-state=running" --format "{{.CurrentState}}" | grep -i "Running" | wc -l)
              
              HEALTHY_STATUS_COUNT=$(docker service ps "$SERVICE_NAME" --no-trunc --format "{{.CurrentState}}" | grep -i "healthy" | wc -l)
              
              HEALTH_STATUS="unknown"
              if [ "$HEALTHY_STATUS_COUNT" -ge "$REPLICAS_EXPECTED" ]; then
                  HEALTH_STATUS="healthy"
              elif [ "$RUNNING_REPLICAS" -ge "$REPLICAS_EXPECTED" ]; then
                  HEALTH_STATUS="starting_or_unhealthy"
              else
                  HEALTH_STATUS="not_running_or_starting"
              fi

              echo "  Attempt $((ATTEMPTS+1))/$MAX_ATTEMPTS: Service '$SERVICE_NAME' - Running: $RUNNING_REPLICAS/$REPLICAS_EXPECTED. Health: $HEALTH_STATUS."

              if [ "$RUNNING_REPLICAS" -ge "$REPLICAS_EXPECTED" ] && [ "$HEALTH_STATUS" == "healthy" ]; then
                echo "Service '$SERVICE_NAME' is running and healthy. Deployment successful!"
                break
              fi
              
              sleep 5
              ATTEMPTS=$((ATTEMPTS+1))
            done

            if [ $ATTEMPTS -eq $MAX_ATTEMPTS ]; then
              echo "Error: Service '$SERVICE_NAME' did not become stable (healthy and running) after $MAX_ATTEMPTS attempts. Deployment failed."
              exit 1
            fi