name: Orchestrate All Services Deployment

on:
  push:
    branches:
      - master
    paths:
      - 'api-gateway/**'
      - 'auth-service/**'

  workflow_dispatch:

jobs:
  deploy_auth_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call Deploy Auth Service Workflow
        uses: ./.github/workflows/reusable/deploy-auth-service.yml@master
        with:
          service_path: auth-service
          vps_target_path: /var/www/auth-service/
        secrets:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

  deploy_api_gateway:
    runs-on: ubuntu-latest
    needs: [deploy_auth_service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call Deploy API Gateway Workflow
        uses: ./.github/workflows/reusable/deploy-api-gateway.yml@master
        with:
          service_path: api-gateway
          vps_target_path: /var/www/api-gateway/
        secrets:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
