# File: PLANBOOK-BE/.github/workflows/deploy-all-service.yml
name: Orchestrate All Services Deployment

on:
  push:
    branches:
      - master # Kích hoạt khi có thay đổi trên nhánh master của monorepo
    paths:
      - 'api-gateway/**' # Chỉ chạy khi có thay đổi trong thư mục api-gateway
      - 'auth-service/**' # Chỉ chạy khi có thay đổi trong thư mục auth-service

  workflow_dispatch: # Cho phép chạy thủ công từ GitHub UI

jobs:
  deploy_auth_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call Deploy Auth Service Workflow
        uses: ./.github/workflows/reusable/deploy-auth-service.yml@master # Đường dẫn tới reusable workflow của Auth Service
        with:
          service_path: auth-service # Truyền đường dẫn của service con trong monorepo
          vps_target_path: /var/www/be/ # Đường dẫn đích trên VPS cho Auth Service
        secrets: inherit # Truyền tất cả secrets từ workflow cha xuống workflow con

  deploy_api_gateway:
    runs-on: ubuntu-latest
    needs: [deploy_auth_service] # Đảm bảo auth-service được deploy trước
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call Deploy API Gateway Workflow
        uses: ./.github/workflows/reusable/deploy-api-gateway.yml@master # Đường dẫn tới reusable workflow của API Gateway
        with:
          service_path: api-gateway # Truyền đường dẫn của service con trong monorepo
          vps_target_path: /var/www/api-gateway/ # Đường dẫn đích trên VPS cho API Gateway
        secrets: inherit # Truyền tất cả secrets từ workflow cha xuống workflow con