# File: PLANBOOK-BE/.github/workflows/deploy-all-service.yml
name: Orchestrate All Services Deployment

on:
  push:
    branches:
      - master # Kích hoạt khi có thay đổi trên nhánh master của monorepo
      # Thay 'master' bằng 'main' nếu nhánh chính của bạn là 'main'
    paths:
      - 'api-gateway/**' # Chỉ chạy khi có thay đổi trong thư mục api-gateway
      - 'auth-service/**' # Chỉ chạy khi có thay đổi trong thư mục auth-service

  workflow_dispatch: # Cho phép chạy thủ công từ GitHub UI

jobs:
  deploy_auth_service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call Deploy Auth Service Workflow
        uses: ./.github/workflows/reusable/deploy-auth-service.yml@master # Sử dụng ref của nhánh (hoặc tag nếu bạn có)
        # Nếu nhánh chính của bạn là 'main', hãy đổi thành @main
        with:
          service_path: auth-service # Đường dẫn tới thư mục service con trong repo
          vps_target_path: /var/www/auth-service/ # Đường dẫn đích cụ thể cho Auth Service trên VPS
        secrets: inherit # Truyền tất cả secrets từ workflow cha xuống workflow con

  deploy_api_gateway:
    runs-on: ubuntu-latest
    needs: [deploy_auth_service] # Đảm bảo Auth Service được deploy thành công trước
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Call Deploy API Gateway Workflow
        uses: ./.github/workflows/reusable/deploy-api-gateway.yml@master # Sử dụng ref của nhánh (hoặc tag nếu bạn có)
        # Nếu nhánh chính của bạn là 'main', hãy đổi thành @main
        with:
          service_path: api-gateway # Đường dẫn tới thư mục service con trong repo
          vps_target_path: /var/www/api-gateway/ # Đường dẫn đích cụ thể cho API Gateway trên VPS
        secrets: inherit # Truyền tất cả secrets từ workflow cha xuống workflow con